/**
 * Gerçek zamanlı sözleşme — web istemcisindeki src/live/socketEvents.js ile
 * BİREBİR aynı olmalıdır. Sunucu (lib/socket.js) bu adlarla yayın yapar.
 */
export const SOCKET_EVENTS = Object.freeze({
  JOIN_MATCH: "join-match",
  LEAVE_MATCH: "leave-match",
  RESYNC: "MATCH_RESYNC_REQUIRED",
  STATE_UPDATED: "MATCH_STATE_UPDATED",
  EVENT_CREATED: "MATCH_EVENT_CREATED",
  EVENT_UPDATED: "MATCH_EVENT_UPDATED",
  EVENT_DELETED: "MATCH_EVENT_DELETED",
  TIMER_UPDATED: "MATCH_TIMER_UPDATED",
  SCORE_UPDATED: "MATCH_SCORE_UPDATED",
  LINEUP_UPDATED: "MATCH_LINEUP_UPDATED",
  STATUS_UPDATED: "MATCH_STATUS_UPDATED",
});

/** Anlık görüntüyü baştan çekmeyi gerektiren olaylar. */
export const RESNAPSHOT_EVENTS = [
  SOCKET_EVENTS.RESYNC,
  SOCKET_EVENTS.STATE_UPDATED,
  SOCKET_EVENTS.EVENT_CREATED,
  SOCKET_EVENTS.EVENT_UPDATED,
  SOCKET_EVENTS.EVENT_DELETED,
  SOCKET_EVENTS.SCORE_UPDATED,
  SOCKET_EVENTS.LINEUP_UPDATED,
  SOCKET_EVENTS.STATUS_UPDATED,
  SOCKET_EVENTS.TIMER_UPDATED,
];
